# -*- coding: utf-8 -*-
"""Assignment 2 Breast Cancer .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4hNF9_WmibRJMqnOYfdHQfdbmG691N5
"""

import pandas as pd
import numpy as np

data=pd.read_csv('dataR2.csv')

data.head()

data.describe()

data.isna().sum()

x=data.drop('Classification',axis=1)
y=data['Classification']

x.head()

y.head()

y

#splitting to the train and test data for both dataset "Data", "Data2"
from sklearn.model_selection import train_test_split
x_train,x_validate,y_train,y_validate = train_test_split(x,y, test_size=0.20,random_state=1, stratify=y)

#Importing Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
y_predict=lr.predict(x_validate)
acu=accuracy_score(y_validate,y_predict)
acu

import pickle
filename = 'Dwij_LRmodel_v1.sav'
pickle.dump(lr, open(filename, 'wb'))

from sklearn import svm
clf = svm.SVC()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_validate)

acu_SVM=accuracy_score(y_validate,y_pred)
acu_SVM

import pickle
filename = 'Dwij_SVMmodel_v1.sav'
pickle.dump(clf, open(filename, 'wb'))

